# Generated by Django 4.0.3 on 2022-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('newstopic', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=500)),
                ('newssource', models.CharField(max_length=500)),
                ('uploadtime', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('plabel', models.CharField(max_length=50))
            ],
        ),
    ]
